# Namespace where the Cassandra Cluster will be created
apiVersion: v1
kind: Namespace
metadata:
  name: rook-cassandra

---

# Role for cassandra members.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rook-cassandra-member
  namespace: rook-cassandra
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - cassandra.rook.io
    resources:
      - clusters
    verbs:
      - get

---

# ServiceAccount for cassandra members.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-cassandra-member
  namespace: rook-cassandra

---

# RoleBinding for cassandra members.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rook-cassandra-member
  namespace: rook-cassandra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-cassandra-member
subjects:
- kind: ServiceAccount
  name: rook-cassandra-member
  namespace: rook-cassandra

---

# Cassandra Cluster
apiVersion: cassandra.rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-cassandra
  namespace: rook-cassandra
  annotations:
    cassandra.rook.io/cpu-pinning: "true"
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9180'
spec:
  version: 2.3.1
  mode: scylla
  datacenter:
    name: us-west1
    racks:
      - name: us-west1-b
        members: 2
        storage:
          volumeClaimTemplates:
                - metadata:
                    name: rook-cassandra-data
                  spec:
                    storageClassName: local-raid-disks
                    resources:
                      requests:
                        storage: 100Gi
        resources:
          limits:
            cpu: 30
            memory: 115G
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/region
                    operator: In
                    values:
                      - us-west1
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                      - us-west1-b
                  - key: role
                    operator: In
                    values:
                      - scylla
