
apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-stress-0
  labels:
    app: cassandra-stress
spec:
  template:
    spec:
      containers:
      - name: cassandra-stress
        image: scylladb/scylla:2.3.1
        command:
          - "/bin/bash"
          - "-c"
          - 'cassandra-stress write no-warmup n=20000000 cl=ONE -mode native cql3 connectionsPerHost=60 -col n=FIXED\(5\) size=FIXED\(64\)  -pop seq=1..20000000 -node "10.35.249.151" -rate threads=400 limit=50000/s -log file=/cassandra-stress.load.data -schema "replication(factor=2)" -errors ignore; cat /cassandra-stress.load.data'
        resources:
          limits:
            cpu: 5
            memory: 20G
      restartPolicy: Never
      nodeSelector:
        role: cassandra-stress
      # affinity:
      #   podAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #       - podAffinityTerm:
      #           labelSelector:
      #             matchLabels:
      #               app: cassandra-stress
         

---

apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-stress-1
  labels:
    app: cassandra-stress
spec:
  template:
    spec:
      containers:
      - name: cassandra-stress
        image: scylladb/scylla:2.3.1
        command:
          - "/bin/bash"
          - "-c"
          - 'cassandra-stress write no-warmup n=20000000 cl=ONE -mode native cql3 connectionsPerHost=60 -col n=FIXED\(5\) size=FIXED\(64\)  -pop seq=20000001..40000000 -node "10.35.249.151" -rate threads=400 limit=50000/s -log file=/cassandra-stress.load.data -schema "replication(factor=2)" -errors ignore; cat /cassandra-stress.load.data'
        resources:
          limits:
            cpu: 5
            memory: 20G
      restartPolicy: Never
      nodeSelector:
        role: cassandra-stress
      # affinity:
      #   podAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #       - podAffinityTerm:
      #           labelSelector:
      #             matchLabels:
      #               app: cassandra-stress
         

---

apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-stress-2
  labels:
    app: cassandra-stress
spec:
  template:
    spec:
      containers:
      - name: cassandra-stress
        image: scylladb/scylla:2.3.1
        command:
          - "/bin/bash"
          - "-c"
          - 'cassandra-stress write no-warmup n=20000000 cl=ONE -mode native cql3 connectionsPerHost=60 -col n=FIXED\(5\) size=FIXED\(64\)  -pop seq=40000001..60000000 -node "10.35.249.151" -rate threads=400 limit=50000/s -log file=/cassandra-stress.load.data -schema "replication(factor=2)" -errors ignore; cat /cassandra-stress.load.data'
        resources:
          limits:
            cpu: 5
            memory: 20G
      restartPolicy: Never
      nodeSelector:
        role: cassandra-stress
      # affinity:
      #   podAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #       - podAffinityTerm:
      #           labelSelector:
      #             matchLabels:
      #               app: cassandra-stress
         

---

apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-stress-3
  labels:
    app: cassandra-stress
spec:
  template:
    spec:
      containers:
      - name: cassandra-stress
        image: scylladb/scylla:2.3.1
        command:
          - "/bin/bash"
          - "-c"
          - 'cassandra-stress write no-warmup n=20000000 cl=ONE -mode native cql3 connectionsPerHost=60 -col n=FIXED\(5\) size=FIXED\(64\)  -pop seq=60000001..80000000 -node "10.35.249.151" -rate threads=400 limit=50000/s -log file=/cassandra-stress.load.data -schema "replication(factor=2)" -errors ignore; cat /cassandra-stress.load.data'
        resources:
          limits:
            cpu: 5
            memory: 20G
      restartPolicy: Never
      nodeSelector:
        role: cassandra-stress
      # affinity:
      #   podAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #       - podAffinityTerm:
      #           labelSelector:
      #             matchLabels:
      #               app: cassandra-stress
         

---

apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-stress-4
  labels:
    app: cassandra-stress
spec:
  template:
    spec:
      containers:
      - name: cassandra-stress
        image: scylladb/scylla:2.3.1
        command:
          - "/bin/bash"
          - "-c"
          - 'cassandra-stress write no-warmup n=20000000 cl=ONE -mode native cql3 connectionsPerHost=60 -col n=FIXED\(5\) size=FIXED\(64\)  -pop seq=80000001..100000000 -node "10.35.249.151" -rate threads=400 limit=50000/s -log file=/cassandra-stress.load.data -schema "replication(factor=2)" -errors ignore; cat /cassandra-stress.load.data'
        resources:
          limits:
            cpu: 5
            memory: 20G
      restartPolicy: Never
      nodeSelector:
        role: cassandra-stress
      # affinity:
      #   podAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #       - podAffinityTerm:
      #           labelSelector:
      #             matchLabels:
      #               app: cassandra-stress
         

---

apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-stress-5
  labels:
    app: cassandra-stress
spec:
  template:
    spec:
      containers:
      - name: cassandra-stress
        image: scylladb/scylla:2.3.1
        command:
          - "/bin/bash"
          - "-c"
          - 'cassandra-stress write no-warmup n=20000000 cl=ONE -mode native cql3 connectionsPerHost=60 -col n=FIXED\(5\) size=FIXED\(64\)  -pop seq=100000001..120000000 -node "10.35.249.151" -rate threads=400 limit=50000/s -log file=/cassandra-stress.load.data -schema "replication(factor=2)" -errors ignore; cat /cassandra-stress.load.data'
        resources:
          limits:
            cpu: 5
            memory: 20G
      restartPolicy: Never
      nodeSelector:
        role: cassandra-stress
      # affinity:
      #   podAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #       - podAffinityTerm:
      #           labelSelector:
      #             matchLabels:
      #               app: cassandra-stress
         
